In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re # For regular expressios with Python

Read dataset

In [3]:
# Reading MIT-BIH Arrhythmia Dataset as an example
data_df = pd.read_csv('MIT-BIH Arrhythmia Database.csv') 
print(data_df.shape)
data_df.head()

(100689, 34)


record type  0_pre-RR  0_post-RR   0_pPeak   0_tPeak   0_rPeak   0_sPeak  \
0     101    N        76      313.0  0.074347 -0.160548  1.036401 -0.285662   
1     101    N       313      315.0 -0.052079 -0.264784  0.886597 -0.366298   
2     101    N       315      321.0 -0.062151 -0.296983  0.991859 -0.410306   
3     101    N       321      336.0 -0.063322 -0.281386  1.034903 -0.403880   
4     101    N       336      344.0 -0.062915  1.046914  1.046408  1.046408   

    0_qPeak  0_qrs_interval  ...   1_qPeak  1_qrs_interval  1_pq_interval  \
0 -0.026824              41  ...  0.025930               2             18   
1 -0.059710              21  ... -0.042009              26             27   
2 -0.065686              22  ...  0.009528               3              8   
3 -0.071750              22  ... -0.020536               6              9   
4 -0.074639              11  ...  0.016053              16              5   

   1_qt_interval  1_st_interval  1_qrs_morph0  1_qrs_morph1  1_qrs_morph2  \
0             22              2      0.025930      0.025930      0.025930   
1             62              9     -0.042009     -0.029498      0.005012   
2             12              1      0.009528      0.009528      0.008786   
3             16              1     -0.020536     -0.020257     -0.018965   
4             31             10      0.016053      0.006742      0.002782   

   1_qrs_morph3  1_qrs_morph4  
0      0.025436      0.025436  
1      0.030892      0.002986  
2      0.008786      0.008368  
3     -0.016968     -0.014555  
4     -0.007798     -0.051155  

[5 rows x 34 columns]

In [4]:
qrs_morph_columns = [col for col in data_df.columns if re.search(r'\d+_qrs_morph\d+', col)]

data_df_no_morph = data_df.drop(columns=qrs_morph_columns)

In [5]:
data_df_no_morph.head()

record type  0_pre-RR  0_post-RR   0_pPeak   0_tPeak   0_rPeak   0_sPeak  \
0     101    N        76      313.0  0.074347 -0.160548  1.036401 -0.285662   
1     101    N       313      315.0 -0.052079 -0.264784  0.886597 -0.366298   
2     101    N       315      321.0 -0.062151 -0.296983  0.991859 -0.410306   
3     101    N       321      336.0 -0.063322 -0.281386  1.034903 -0.403880   
4     101    N       336      344.0 -0.062915  1.046914  1.046408  1.046408   

    0_qPeak  0_qrs_interval  ...  1_post-RR   1_pPeak   1_tPeak   1_rPeak  \
0 -0.026824              41  ...      313.0  0.038310  0.025784  0.025930   
1 -0.059710              21  ...      315.0  0.014264  0.045458  0.032573   
2 -0.065686              22  ...      321.0  0.021311  0.008246  0.009528   
3 -0.071750              22  ...      336.0 -0.000665 -0.009725 -0.010203   
4 -0.074639              11  ...      344.0  0.024559  0.016925  0.016053   

    1_sPeak   1_qPeak  1_qrs_interval  1_pq_interval  1_qt_interval  \
0  0.025271  0.025930               2             18             22   
1 -0.104503 -0.042009              26             27             62   
2  0.008230  0.009528               3              8             12   
3 -0.010203 -0.020536               6              9             16   
4 -0.099918  0.016053              16              5             31   

   1_st_interval  
0              2  
1              9  
2              1  
3              1  
4             10  

[5 rows x 24 columns]

In [7]:
data_df_no_morph.dtypes

record              int64
type               object
0_pre-RR            int64
0_post-RR         float64
0_pPeak           float64
0_tPeak           float64
0_rPeak           float64
0_sPeak           float64
0_qPeak           float64
0_qrs_interval      int64
0_pq_interval       int64
0_qt_interval       int64
0_st_interval       int64
1_pre-RR            int64
1_post-RR         float64
1_pPeak           float64
1_tPeak           float64
1_rPeak           float64
1_sPeak           float64
1_qPeak           float64
1_qrs_interval      int64
1_pq_interval       int64
1_qt_interval       int64
1_st_interval       int64
dtype: object

Split the data into features and class labels

In [21]:
x_data = data_df_no_morph.iloc[:, 2:].copy()
y_label = data_df_no_morph[['type']].copy()

In [22]:
x_data.head()

0_pre-RR  0_post-RR   0_pPeak   0_tPeak   0_rPeak   0_sPeak   0_qPeak  \
0        76      313.0  0.074347 -0.160548  1.036401 -0.285662 -0.026824   
1       313      315.0 -0.052079 -0.264784  0.886597 -0.366298 -0.059710   
2       315      321.0 -0.062151 -0.296983  0.991859 -0.410306 -0.065686   
3       321      336.0 -0.063322 -0.281386  1.034903 -0.403880 -0.071750   
4       336      344.0 -0.062915  1.046914  1.046408  1.046408 -0.074639   

   0_qrs_interval  0_pq_interval  0_qt_interval  ...  1_post-RR   1_pPeak  \
0              41             18             66  ...      313.0  0.038310   
1              21              4             33  ...      315.0  0.014264   
2              22              3             32  ...      321.0  0.021311   
3              22              4             33  ...      336.0 -0.000665   
4              11              4             16  ...      344.0  0.024559   

    1_tPeak   1_rPeak   1_sPeak   1_qPeak  1_qrs_interval  1_pq_interval  \
0  0.025784  0.025930  0.025271  0.025930               2             18   
1  0.045458  0.032573 -0.104503 -0.042009              26             27   
2  0.008246  0.009528  0.008230  0.009528               3              8   
3 -0.009725 -0.010203 -0.010203 -0.020536               6              9   
4  0.016925  0.016053 -0.099918  0.016053              16              5   

   1_qt_interval  1_st_interval  
0             22              2  
1             62              9  
2             12              1  
3             16              1  
4             31             10  

[5 rows x 22 columns]

In [23]:
y_label.value_counts()

type
N       90083
VEB      7009
SVEB     2779
F         803
Q          15
Name: count, dtype: int64

In [24]:
# Transform multi-class labels into binary-class (arrhythmia and normal)
y_label.replace(['VEB', 'SVEB', 'F', 'Q'], 'arrhythmia', inplace=True)
y_label.replace(['N'], 'normal', inplace=True)

#y_label.loc[y_label['type'].isin(['VEB', 'SVEB', 'F', 'Q']), 'type'] = 'arrhythmia'
#y_label.loc[y_label['type'] == 'N', 'type'] = 'normal'

In [25]:
y_label.value_counts()

type      
normal        90083
arrhythmia    10606
Name: count, dtype: int64

Train-test Split

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data, y_label, random_state=101)

Feature Scaling

In [26]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_train_scaled = min_max_scaler.fit_transform(X_train)
X_test_scaled = min_max_scaler.transform(X_test)

print(min_max_scaler.scale_)

[0.00047847 0.00047438 0.14497051 0.163272   0.15645161 0.13086489
 0.14384207 0.00588235 0.00671141 0.00303951 0.00714286 0.00047847
 0.00047438 0.13755979 0.10530541 0.12688961 0.10556911 0.10509129
 0.00456621 0.00543478 0.002457   0.00531915]


In [27]:
X_train_scaled

array([[0.15263158, 0.15512334, 0.44506625, ..., 0.04891304, 0.04176904,
        0.05319149],
       [0.08277512, 0.09250474, 0.45011298, ..., 0.01086957, 0.04914005,
        0.05851064],
       [0.13349282, 0.09250474, 0.45430416, ..., 0.10326087, 0.0982801 ,
        0.10106383],
       ...,
       [0.10813397, 0.10721063, 0.44058918, ..., 0.05978261, 0.07125307,
        0.        ],
       [0.22583732, 0.14848197, 0.44756388, ..., 0.01630435, 0.03931204,
        0.00531915],
       [0.13971292, 0.15227704, 0.47261668, ..., 0.02173913, 0.07616708,
        0.06382979]])

Model Training

In [40]:
from sklearn.ensemble import RandomForestClassifier

y_train_1d = y_train.values.ravel()  # Convertir a array 1D

model = RandomForestClassifier(random_state=101, n_estimators=150)
#model.fit(X_train_scaled, y_train) # Original
model.fit(X_train_scaled, y_train_1d)

# training accuracy
print('Accuracy for the train data', model.score(X_train_scaled, y_train))

Accuracy for the train data 1.0


Model Testing

In [41]:
from sklearn import metrics
y_pred = model.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print("*** Confusion Matrix ***")
print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.9900289993246733
*** Confusion Matrix ***
[[ 2388   193]
 [   58 22534]]


Export model

In [103]:
import joblib

# Save model in a file
joblib.dump((model, min_max_scaler), 'Nehemiah.pkl')

['Nehemiah.pkl']

Gemini

Entiendo. El error "UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names" indica que el objeto MinMaxScaler se ajustó con datos que tenían nombres de características (columnas), pero ahora se está utilizando para transformar datos que no tienen nombres de características.

Esto puede suceder si estás utilizando un DataFrame de Pandas para entrenar el modelo y ajustar el escalador, pero luego estás utilizando un array NumPy para hacer predicciones. Los arrays NumPy no tienen nombres de características, por lo que el escalador no puede encontrar las características que espera.

Para solucionar este problema, puedes intentar lo siguiente:

1. Utilizar un DataFrame de Pandas para hacer predicciones:
Si es posible, utiliza un DataFrame de Pandas para almacenar los datos de entrada que se utilizarán para hacer predicciones. Asegúrate de que el DataFrame tenga los mismos nombres de columnas que el DataFrame que se utilizó para entrenar el modelo y ajustar el escalador.

2. Asignar nombres de características al array NumPy:
Si no puedes utilizar un DataFrame de Pandas, puedes asignar nombres de características al array NumPy utilizando la función np.array con el argumento dtype:

In [ ]:
input_data = np.array(input_data, dtype=[('feature1', float), ('feature2', float), ...])

Reemplaza feature1, feature2, etc. con los nombres de las características que espera el escalador.

3. Ignorar la advertencia:
Si la advertencia no afecta el rendimiento del modelo, puedes ignorarla utilizando la función warnings.filterwarnings:

In [ ]:
import warnings

warnings.filterwarnings('ignore', message='X does not have valid feature names, but')

Esto ignorará todas las advertencias que contengan la frase "X does not have valid feature names, but".

Espero que alguna de estas soluciones te ayude a resolver el problema. Si aún tienes problemas, por favor, proporciona más detalles sobre el código que estás utilizando para que pueda ayudarte mejor.

Gemini

Input feature scaling

In [99]:
new0 = [76,313,0.07434712,-0.160547951,1.036401408,-0.285662496,-0.026823649,41,18,66,7,76,313,0.038309507,0.025784325,0.025930319,0.02527078,0.025930319,2,18,22,2] # N
new1 = [313,315,-0.052078893,-0.264784292,0.886596913,-0.366297705,-0.059710405,21,4,33,8,313,315,0.014263639,0.045458043,0.032572702,-0.104502953,-0.042008529,26,27,62,9] # N
new2 = [151,439,0.463362235,0.519227559,0.399900123,-0.835039794,-0.206610994,47,39,171,85,151,439,-0.277927062,-0.273391493,-0.574060719,-0.597215122,-0.574060719,2,11,23,10] # VEB

new_2d = np.reshape(new2, (1, -1))
new_2d_scale = min_max_scaler.transform(new_2d)
new_2d_scale = new_2d_scale.flatten()
#new_2d_scale = new_2d_scale.reshape(1, -1)

prediccion0 = model.predict([new_2d_scale])

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [100]:
prediccion0

array(['arrhythmia'], dtype=object)

In [84]:
new_2d_scale

array([0.06076555, 0.20540797, 0.51576931, 0.41236779, 0.43379879,
       0.36478728, 0.52714496, 0.27647059, 0.25503356, 0.50455927,
       0.6       , 0.06076555, 0.20540797, 0.25177973, 0.2337888 ,
       0.41534152, 0.58671697, 0.5157798 , 0.00913242, 0.05434783,
       0.04422604, 0.04787234])

In [50]:
#import wfdb