In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

Read dataset

In [2]:
# Reading MIT-BIH Arrhythmia Dataset as an example
data_df = pd.read_csv('MIT-BIH Arrhythmia Database.csv') 
print(data_df.shape)
data_df.head()

(100689, 34)


record type  0_pre-RR  0_post-RR   0_pPeak   0_tPeak   0_rPeak   0_sPeak  \
0     101    N        76      313.0  0.074347 -0.160548  1.036401 -0.285662   
1     101    N       313      315.0 -0.052079 -0.264784  0.886597 -0.366298   
2     101    N       315      321.0 -0.062151 -0.296983  0.991859 -0.410306   
3     101    N       321      336.0 -0.063322 -0.281386  1.034903 -0.403880   
4     101    N       336      344.0 -0.062915  1.046914  1.046408  1.046408   

    0_qPeak  0_qrs_interval  ...   1_qPeak  1_qrs_interval  1_pq_interval  \
0 -0.026824              41  ...  0.025930               2             18   
1 -0.059710              21  ... -0.042009              26             27   
2 -0.065686              22  ...  0.009528               3              8   
3 -0.071750              22  ... -0.020536               6              9   
4 -0.074639              11  ...  0.016053              16              5   

   1_qt_interval  1_st_interval  1_qrs_morph0  1_qrs_morph1  1_qrs_morph2  \
0             22              2      0.025930      0.025930      0.025930   
1             62              9     -0.042009     -0.029498      0.005012   
2             12              1      0.009528      0.009528      0.008786   
3             16              1     -0.020536     -0.020257     -0.018965   
4             31             10      0.016053      0.006742      0.002782   

   1_qrs_morph3  1_qrs_morph4  
0      0.025436      0.025436  
1      0.030892      0.002986  
2      0.008786      0.008368  
3     -0.016968     -0.014555  
4     -0.007798     -0.051155  

[5 rows x 34 columns]

Split the data into features and class labels

In [3]:
x_data = data_df.iloc[:, 2:]
y_label = data_df[['type']]

In [4]:
x_data.head()

0_pre-RR  0_post-RR   0_pPeak   0_tPeak   0_rPeak   0_sPeak   0_qPeak  \
0        76      313.0  0.074347 -0.160548  1.036401 -0.285662 -0.026824   
1       313      315.0 -0.052079 -0.264784  0.886597 -0.366298 -0.059710   
2       315      321.0 -0.062151 -0.296983  0.991859 -0.410306 -0.065686   
3       321      336.0 -0.063322 -0.281386  1.034903 -0.403880 -0.071750   
4       336      344.0 -0.062915  1.046914  1.046408  1.046408 -0.074639   

   0_qrs_interval  0_pq_interval  0_qt_interval  ...   1_qPeak  \
0              41             18             66  ...  0.025930   
1              21              4             33  ... -0.042009   
2              22              3             32  ...  0.009528   
3              22              4             33  ... -0.020536   
4              11              4             16  ...  0.016053   

   1_qrs_interval  1_pq_interval  1_qt_interval  1_st_interval  1_qrs_morph0  \
0               2             18             22              2      0.025930   
1              26             27             62              9     -0.042009   
2               3              8             12              1      0.009528   
3               6              9             16              1     -0.020536   
4              16              5             31             10      0.016053   

   1_qrs_morph1  1_qrs_morph2  1_qrs_morph3  1_qrs_morph4  
0      0.025930      0.025930      0.025436      0.025436  
1     -0.029498      0.005012      0.030892      0.002986  
2      0.009528      0.008786      0.008786      0.008368  
3     -0.020257     -0.018965     -0.016968     -0.014555  
4      0.006742      0.002782     -0.007798     -0.051155  

[5 rows x 32 columns]

In [5]:
y_label.value_counts()

type
N       90083
VEB      7009
SVEB     2779
F         803
Q          15
Name: count, dtype: int64

In [6]:
# Transform multi-class labels into binary-class (arrhythmia and normal)
y_label.replace(['VEB', 'SVEB', 'F', 'Q'], 'arrhythmia', inplace=True)
y_label.replace(['N'], 'normal', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_13912\1460342108.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_label.replace(['VEB', 'SVEB', 'F', 'Q'], 'arrhythmia', inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_13912\1460342108.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_label.replace(['N'], 'normal', inplace=True)


In [7]:
y_label.value_counts()

type      
normal        90083
arrhythmia    10606
Name: count, dtype: int64

Train-test Split

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data, y_label, random_state=101)

Feature Scaling

In [9]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_train_scaled = min_max_scaler.fit_transform(X_train)
X_test_scaled = min_max_scaler.transform(X_test)

print(min_max_scaler.scale_)

[0.00047847 0.00047438 0.14497051 0.163272   0.15645161 0.13086489
 0.14384207 0.00588235 0.00671141 0.00303951 0.00714286 0.14384207
 0.18186031 0.16202895 0.16077164 0.17486125 0.00047847 0.00047438
 0.13755979 0.10530541 0.12688961 0.10556911 0.10509129 0.00456621
 0.00543478 0.002457   0.00531915 0.10509129 0.12377001 0.1410501
 0.15095282 0.13532692]


In [10]:
X_train_scaled

array([[0.15263158, 0.15512334, 0.44506625, ..., 0.56929435, 0.55969046,
        0.56273247],
       [0.08277512, 0.09250474, 0.45011298, ..., 0.59357774, 0.57069667,
        0.56241605],
       [0.13349282, 0.09250474, 0.45430416, ..., 0.60071605, 0.58812537,
        0.58465607],
       ...,
       [0.10813397, 0.10721063, 0.44058918, ..., 0.61391008, 0.62145807,
        0.64784558],
       [0.22583732, 0.14848197, 0.44756388, ..., 0.62804987, 0.6482734 ,
        0.68251227],
       [0.13971292, 0.15227704, 0.47261668, ..., 0.63284376, 0.62555943,
        0.58376543]])

Model Training

In [11]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=101, n_estimators=150)
model.fit(X_train_scaled, y_train)

# training accuracy
print('Accuracy for the train data', model.score(X_train_scaled, y_train))

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Accuracy for the train data 1.0


Model Testing

In [14]:
from sklearn import metrics
y_pred = model.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

print("*** Confusion Matrix ***")
print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.9901084495292576
*** Confusion Matrix ***
[[ 2389   192]
 [   57 22535]]


In [50]:
nueva_persona = [76,313.0,0.07434712002287082,-0.16054795129099128,1.0364014078032489,-0.2856624960264329,-0.026823649006672383,41,18,66,7,-0.026823649006672383,-0.0012361169818203436,0.016658510642772642,0.1432411711717847,0.996287443844827,76,313.0,0.03830950702022621,0.02578432495409821,0.025930319366613813,0.025270779635925975,0.025930319366613813,2,18,22,2,0.025930319366613813,0.025930319366613813,0.025930319366613813,0.02543618012812314,0.02543618012812314]
nueva_persona1 = [313,315.0,-0.05207889285793339,-0.2647842920445563,0.8865969132633993,-0.36629770463713696,-0.059710405355239964,21,4,33,8,-0.059710405355239964,0.10403043107831474,0.6918910779780433,0.8055492370403278,0.08406854461239475,313,315.0,0.01426363933757646,0.04545804328049541,0.03257270152401111,-0.10450295310146211,-0.04200852934012642,26,27,62,9,-0.04200852934012642,-0.029497609296578076,0.005011963852684208,0.03089154454616144,0.002985600629510798]
nueva_persona2 = [324,313.0,-0.06752006183815168,-0.2869339060840042,1.0505454910300114,-0.4828861704474081,-0.07466602385101427,23,3,34,8,-0.07466602385101427,0.0023637460949844126,0.7152338231624668,1.00985322893769,-0.024538360426868314,324,313.0,-0.012952933626593057,0.02144770236975216,0.0355038812628328,-0.0596581539090673,-0.03278774239465794,27,10,45,8,-0.03278774239465794,-0.017466871332908477,0.013925012448165524,0.035175838419478286,0.016576486898321672]
nueva_persona3 = [175,256.0,-0.0861167456473892,0.8990458905825645,-0.004377651329598621,-0.004377651329598621,-0.09535232222019246,3,4,14,7,-0.09535232222019246,-0.09535232222019246,-0.08555791992418688,-0.08555791992418688,-0.057828999126116026,175,256.0,0.0018616582512705282,0.03882075371063194,0.07227570276961409,-0.18820546536924238,-0.004782893504585362,21,7,44,16,-0.004782893504585362,0.01788785856842645,0.06388475064689159,0.06279316635192886,-0.05162262751883227]
#prediccion = model.predict([nueva_persona1])
nueva_persona_2d = np.reshape(nueva_persona3, (1, -1))  # Convierte a un array 2D con una sola fila
nueva_persona_scale = min_max_scaler.transform(nueva_persona_2d)
nueva_persona_scale = nueva_persona_scale.flatten()  # Convierte a un array 1D
#nueva_persona_scale = nueva_persona_scale.reshape(1, -1)  # Convierte a un array 2D con una sola fila
#prediccion = model.predict(nueva_persona_scale)
prediccion = model.predict([nueva_persona_scale])

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [53]:
prediccion

array(['arrhythmia'], dtype=object)

In [51]:
nueva_persona_scale

array([0.0722488 , 0.11859583, 0.43611106, 0.47438149, 0.37054888,
       0.47349179, 0.54314863, 0.01764706, 0.02013423, 0.02735562,
       0.04285714, 0.54314863, 0.46077579, 0.44636582, 0.4677886 ,
       0.52952653, 0.0722488 , 0.11859583, 0.29026741, 0.26666644,
       0.49735489, 0.62989575, 0.57560594, 0.09589041, 0.0326087 ,
       0.0958231 , 0.07978723, 0.57560594, 0.55840963, 0.62936654,
       0.62381536, 0.60473594])

In [ ]:
nueva_persona_2d = np.reshape(nueva_persona3, (1, -1))
nueva_persona_scale = min_max_scaler.transform(nueva_persona_2d)
nueva_persona_scale = nueva_persona_scale.flatten()
nueva_persona_scale = nueva_persona_scale.reshape(1, -1)
prediccion = model.predict(nueva_persona_scale)

In [30]:
nueva_persona_scale

array([[0.02488038, 0.14563567, 0.45937359, 0.30137949, 0.53338043,
        0.43668148, 0.55300594, 0.24117647, 0.11409396, 0.18541033,
        0.04285714, 0.55300594, 0.47789179, 0.46292784, 0.504573  ,
        0.71385065, 0.02488038, 0.14563567, 0.29528117, 0.26529363,
        0.49147415, 0.65243225, 0.57883363, 0.00913242, 0.0923913 ,
        0.04176904, 0.00531915, 0.57883363, 0.55940505, 0.62401307,
        0.61817622, 0.61516407]])

In [52]:
prediccion

array(['arrhythmia'], dtype=object)

In [ ]:
# Cargar los datos de entrada
input_data = pd.read_csv('input_data.csv')  # Reemplaza 'input_data.csv' con el nombre de tu archivo

# Eliminar las morph features de los datos de entrada
input_data_no_morph = input_data.drop(columns=morphology_columns)  # morphology_columns debe ser la misma lista que usaste para los datos de entrenamiento

# Preprocesar los datos de entrada con MinMaxScaler
input_data_scaled = min_max_scaler.transform(input_data_no_morph)  # min_max_scaler debe ser el mismo objeto que usaste para los datos de entrenamiento

# Hacer predicciones con el modelo
predictions = model.predict(input_data_scaled)

In [ ]:
#import wfdb